[package]
name = "RS-SnowF"
version = "0.1.0"
authors = ["zhouzj <zhouzj@zhouzj.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
lazy_static = "1.4.0"

